version: "3"

services:

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    env_file: .env
    expose:
      - "3306/tcp"
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - internal
    restart: always

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    env_file: .env
    depends_on: 
      - mariadb
    expose:
      - "9000/tcp"
    networks:
      - internal
    volumes:
      - wordpress_volume:/var/www/html
    restart: always

  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - internal
    volumes:
      - wordpress_volume:/var/www/html
    depends_on: 
      - wordpress
    restart: always

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/jberredj/data/mariadb
      o: bind
  
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/jberredj/data/wordpress
      o: bind

networks:
  internal: