FROM debian:buster

RUN apt update && apt install mariadb-server dumb-init -y

RUN mkdir -p /var/run/mysqld && mkdir -p /run/mysqld
RUN chown -R mysql:root /run/mysqld && chown -R mysql:root /var/run/mysqld

COPY tools/launch.sh /var/launch.sh
RUN chmod +x /var/launch.sh
COPY conf/mariadb.conf /etc/mysql/mariadb.conf.d/50-server.cnf

EXPOSE 3306

ENTRYPOINT [ "/usr/bin/dumb-init", "--" ]
CMD [ "/var/launch.sh" ]