FROM debian:buster

RUN apt update && apt install php7.3 php7.3-fpm php7.3-mysql php-common php7.3-cli php7.3-common \
	php7.3-json php7.3-opcache php7.3-readline php-curl php-gd php-intl php-mbstring php-soap \
	php-xml php-xmlrpc php-zip dumb-init curl mariadb-client -y


COPY tools/launch.sh /var/launch.sh
COPY conf/www.conf /etc/php/7.3/fpm/pool.d
RUN mkdir /run/php

RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
	chmod +x wp-cli.phar && \
	mv wp-cli.phar /usr/local/bin/wp

EXPOSE 9000

# Dumb-init use as PID 1 Sig Handler
ENTRYPOINT [ "/usr/bin/dumb-init", "--" ]
CMD [ "/var/launch.sh" ]